### PR TITLE
feat: `externals` in HtmlWebpackPlugin options

### PR DESCRIPTION
**Pull request by Airkro**
Support `Multiple Page App` tags inject:

```javascript
plugins: [
  new HtmlWebpackPlugin({
    filename: 'index.html'
  }),
  new HtmlWebpackPlugin({
    filename: 'other.html',
    externals: [
      {
        tagName: 'script',
        attributes: {
          src: 'special-script.js'
        }
      }
    ]
  }),
  new HtmlWebpackInjectPlugin({
    externals: [
      {
        tagName: 'script',
        attributes: {
          src: 'common-script.js'
        }
      }
    ]
  })
]
```

To:

```html
<!-- index.html -->
<script src="common-script.js"></script>

<!-- other.html -->
<script src="special-script.js"></script>
<script src="common-script.js"></script>
```

### CODE REVIEW

**Comment by kagawagao** [comment]
`externals` in HtmlWebpackPlugin options?

**Comment by Airkro** [comment]
To support inject different tags to multiple pages.

**Comment by kagawagao** [comment]
maybe use options like `filter` in inject plugin is much better than current plan

https://github.com/kagawagao/html-webpack-inject-plugin/blob/f8f596ee51c1451ecf0abeaef89db698fa39cc36/src/index.ts#L52-L60

ex:

```ts
          this.assets.filter(filter).forEach((asset) => {
            const tagName = (
              asset.tagName !== 'meta' ? `${asset.tagName}s` : asset.tagName
            ) as keyof typeof htmlPluginData.assetTags
            const tags = htmlPluginData.assetTags[tagName]
            htmlPluginData.assetTags[tagName] = this.prepend
              ? [asset].concat(tags)
              : tags.concat(asset)
          })
```

**Comment by Airkro** [comment]
So where is `filter` came from?  HtmlWebpackInjectPlugin.Options.filter?
And how does `filter` divides different HtmlWebpackPlugin instances?.

**Comment by kagawagao** [comment]
please review https://github.com/kagawagao/html-webpack-inject-plugin/commit/6095b6ffc901c4a14fdd0915aa7b7db8e0522725

**Comment by Airkro** [comment]
> please review [6095b6f](https://github.com/kagawagao/html-webpack-inject-plugin/commit/6095b6ffc901c4a14fdd0915aa7b7db8e0522725)

Looks good, just do what you want to do.

For now, I only see differences in personal preference, if there are exact pros and cons please let me know.

**Pull request closed without merging**
